### PR TITLE
login/signup pages done

### PR DESCRIPTION
**Pull request by Joakim-droid**
Sign up page
Screen Shot 2020-09-20 at 19 38 27
Log in page
Screen Shot 2020-09-20 at 19 38 22

### CODE REVIEW

**Comment by b24177** [comment]
Looks great. Can Spotify be written as SPOTIFY so that it matches the text on the other pages like the home page?

**Comment by Joakim-droid** [comment]
I tried, but Spotify isn't text, it's tied to the #{OmniAuth::Utils.camelize(provider)} in _links.html.erb in the shared folder for devise

**Comment by Joakim-droid** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fknowyourmeme.com%2Fmemes%2Fi-pulled-a-sneaky-on-ya&psig=AOvVaw35r4J_lUIBl2LXYmh1-HaI&ust=1600712641738000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCrrLWt-OsCFQAAAAAdAAAAABAD

**Comment by Joakim-droid** [comment]
ross

**Review by b24177 — APPROVED** [review]

**Pull request merged**
