### PR TITLE
custom 404 and 500 pages

### PR DESCRIPTION
**Pull request by Joakim-droid**
Would it be cool if the logo was animated?

### CODE REVIEW

**Comment by b24177** [comment]
Yes!

**Comment by b24177** [comment]
Can you add screenshots?

**Comment by Joakim-droid** [comment]
Screenshot from 2020-10-11 17-08-55
Screenshot from 2020-10-11 17-08-57

**Comment by Joakim-droid** [comment]
They're the same, but I can change it if that's better

**Comment by b24177** [comment]
Looks good to me. Can you just make the logo the same size as it is on the homepage? 64x64.

**Comment by Joakim-droid** [comment]
Screenshot from 2020-10-11 17-45-21
Screenshot from 2020-10-11 17-45-22

**Pull request merged**
