### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by Joakim-droid**
temporary push, home-page is not yet done

### CODE REVIEW

**Comment by b24177** [comment]
Can you add a screenshot of how it looks?

**Comment by Joakim-droid** [comment]
Screenshot from 2020-09-19 18-16-44

**Comment by b24177** [comment]
Yeah, it is definitely getting there! Looking good.

**Comment by Joakim-droid** [comment]
Screenshot from 2020-09-19 22-06-40

**Comment by Joakim-droid** [comment]
Do you have any suggestions to get the paragraph centered?

**Comment by Joakim-droid** [comment]
Screen Shot 2020-09-19 at 22 08 50
The viewport

**Comment by b24177** [comment]
You could try wrapping it in a card with a class name like "card-home". Perhaps that would group the texts together and center them both?

Screenshot 2020-09-20 at 01 11 38

**Comment by Joakim-droid** [comment]
Screen Shot 2020-09-20 at 10 19 26

**Pull request merged**
